# Generated by Django 5.2.9 on 2025-12-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_is_active_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='grade',
            field=models.CharField(choices=[('grade1', 'Grade1'), ('grade2', 'Grade2'), ('grade3', 'Grade3')], default='grade1', max_length=20),
        ),
    ]
